### ISSUE TITLE
Nouveau plan du livre

### ISSUE THREAD

**Issue by KevCaz** [inSileco/VisualiseR#14]
Pour l'instant on pense à structurer le bouquin en 4 parties : 

1. R et les graphiques (il manque une section sur la philosophie des différents packages);
2. base plot;
3. grid & ggplot2;
4. graphiques interactifs du web : une ouverture.

**Comment by david-beauchesne** [comment]
Est-ce que vous avez parlé de distribution de tâche et de timeline pour la suite?

**Comment by KevCaz** [comment]
Voir le fichier 00-outline.Rmd

**Comment by KevCaz** [comment]
Voir #16
