### ISSUE TITLE
Rencontre pour les différents projets

### ISSUE THREAD

**Issue by KevCaz** [inSileco/VisualiseR#4]
J'aimerais bien faire une recontre Slack ou Skype ou autre chose avec ceux qui sont intéressés à contribuer à ce projet.

**Comment by david-beauchesne** [comment]
Je suis intéressé! À quand la rencontre?

**Comment by KevCaz** [comment]
Nous avons eu une première rencontre avec @mhBrice et @ahasverus. On a parlé un peu du contenu. Faudrait peut-être savoir si vous souhaitez qu'il y est une articulation avec le projet d'une formation CSBQ.

**Comment by david-beauchesne** [comment]
J'aurais tendance à dire que oui. Aussi bien maximiser les retours sur l'effort déployé. Par contre, ce n'est pas obligé d'être parfaitement aligné. Essayons de les articuler ensemble, sans toutefois dénaturer les projets.

**Comment by KevCaz** [comment]
La rencontre a eu lieu les projets GH sont en cours et chacun peut apporter sa contribution en choisissant une partie dans l’outline et/ou en suggérant des choses a faire dans l'outline.
